import:
  - ~/.config/alacritty/catppuccin/catppuccin-mocha.yml

env:
  TERM: xterm-256color

key_bindings:
  - { key: Return,   mods: Control|Shift, action: SpawnNewInstance }

colors:
    primary:
        background: '#24272e'
        foreground: '#ffffff'
    cursor:
        text: '#0b0b0b'    # black
        cursor: '#528bff'
    vi_mode_cursor:
        text: '#ffffff'
        cursor: '#333841'
    selection:
        text: '#f1f1f1'
        background: '#3e4452'
    search:
        matches:
            foreground: '#3e4452'
            background: '#e5c07b'
        footer_bar:
            background: '#282c34'
            foreground: '#abb2bf'
    normal:
        black:   '#24272e'
        red:     '#e06c75'
        green:   '#98c379'
        yellow:  '#e5c07b'
        blue:    '#61afef'
        magenta: '#c678dd'
        cyan:    '#56b6c2'
        white:   '#ffffff'
    bright:
        black:   '#3e4452'
        red:     '#be5046'
        green:   '#98c379'
        yellow:  '#d19a66'
        blue:    '#61afef'
        magenta: '#c678dd'
        cyan:    '#56b6c2'
        white:   '#ffffff'

font:
    size: 12
    normal:
        family: SauceCodePro Nerd Font
        style: Regular
    bold:
        family: SauceCodePro Nerd Font
        style: Bold
    italic:
        family: SauceCodePro Nerd Font
        style: Italic
